import 'dart:async';
import '../data/models/course_model.dart';
import '../data/models/user_model.dart';

class MockDataService {
  static final MockDataService _instance = MockDataService._internal();
  factory MockDataService() => _instance;
  MockDataService._internal();

  // Simulate network delay
  Future<void> _simulateDelay() async {
    await Future.delayed(const Duration(milliseconds: 500));
  }

  // Mock courses data
  Future<Map<String, dynamic>> getCourses({
    String? category,
    String? level,
    String? search,
    int page = 1,
    int limit = 50, // Increased to show all courses (28 total)
  }) async {
    await _simulateDelay();

    List<CourseModel> allCourses = _generateMockCourses();

    // Apply filters
    if (category != null && category != 'الكل') {
      allCourses = allCourses.where((c) => c.category == category).toList();
    }
    if (level != null && level != 'الكل') {
      allCourses = allCourses.where((c) => c.level == level).toList();
    }
    if (search != null && search.isNotEmpty) {
      allCourses = allCourses.where((c) =>
        c.title.toLowerCase().contains(search.toLowerCase()) ||
        c.description.toLowerCase().contains(search.toLowerCase())
      ).toList();
    }

    // Apply pagination
    int startIndex = (page - 1) * limit;
    int endIndex = startIndex + limit;
    if (endIndex > allCourses.length) endIndex = allCourses.length;

    List<CourseModel> paginatedCourses = allCourses.sublist(
      startIndex < allCourses.length ? startIndex : 0,
      endIndex,
    );

    return {
      'success': true,
      'courses': paginatedCourses,
      'data': paginatedCourses,
      'pagination': {
        'page': page,
        'limit': limit,
        'total': allCourses.length,
        'pages': (allCourses.length / limit).ceil(),
      }
    };
  }

  Future<Map<String, dynamic>> getCourse(String courseId) async {
    await _simulateDelay();

    final courses = _generateMockCourses();
    final course = courses.firstWhere(
      (c) => c.id == courseId,
      orElse: () => courses.first,
    );

    return {
      'success': true,
      'course': course,
      'data': course,
    };
  }

  Future<Map<String, dynamic>> getEnrolledCourses() async {
    await _simulateDelay();

    // Return first 3 courses as enrolled
    final courses = _generateMockCourses().take(3).toList();

    return {
      'success': true,
      'courses': courses.map((c) => c.toJson()).toList(),
    };
  }

  Future<Map<String, dynamic>> enrollInCourse(String courseId) async {
    await _simulateDelay();

    return {
      'success': true,
      'message': 'تم التسجيل في الدورة بنجاح',
      'data': {
        'courseId': courseId,
        'enrolledAt': DateTime.now().toIso8601String(),
      }
    };
  }

  List<CourseModel> _generateMockCourses() {
    return [
      CourseModel(
        id: '1',
        title: 'أساسيات تعلم الآلة للمبتدئين',
        description: 'تعلم أساسيات الذكاء الاصطناعي وتعلم الآلة من الصفر. دورة شاملة تغطي جميع المفاهيم الأساسية.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=1',
        promoVideoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        instructorId: '1',
        instructorName: 'د. أحمد محمد',
        instructorBio: 'خبير في مجال الذكاء الاصطناعي مع خبرة 10 سنوات',
        instructorPhotoUrl: 'https://picsum.photos/150/150?random=1',
        level: 'مبتدئ',
        category: 'تعلم الآلة',
        isEnrolled: true,
        objectives: [
          'فهم أساسيات تعلم الآلة',
          'بناء نماذج بسيطة',
          'تطبيق الخوارزميات الأساسية',
        ],
        requirements: ['معرفة أساسية بالبرمجة', 'رغبة في التعلم'],
        modules: [
          CourseModule(
            id: 'm1',
            title: 'مقدمة في تعلم الآلة',
            lessons: [
              Lesson(
                id: 'l1',
                title: 'ما هو تعلم الآلة؟',
                videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                duration: const Duration(minutes: 15),
              ),
              Lesson(
                id: 'l2',
                title: 'أنواع تعلم الآلة',
                videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                duration: const Duration(minutes: 20),
              ),
            ],
            duration: const Duration(minutes: 35),
          ),
        ],
        price: 0,
        rating: 4.8,
        totalRatings: 1250,
        enrolledStudents: 5432,
        totalDuration: const Duration(hours: 12),
        createdAt: DateTime.now().subtract(const Duration(days: 30)),
        updatedAt: DateTime.now(),
        isFree: true,
      ),
      CourseModel(
        id: '2',
        title: 'معالجة اللغات الطبيعية المتقدمة',
        description: 'دورة متقدمة في معالجة اللغات الطبيعية باستخدام أحدث التقنيات والنماذج.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=2',
        instructorId: '2',
        instructorName: 'د. سارة أحمد',
        instructorBio: 'باحثة في مجال NLP مع خبرة 8 سنوات',
        level: 'متقدم',
        category: 'معالجة اللغات',
        objectives: [
          'فهم النماذج المتقدمة في NLP',
          'بناء تطبيقات معقدة',
          'استخدام Transformers',
        ],
        requirements: ['خبرة في Python', 'معرفة بأساسيات NLP'],
        modules: [],
        price: 299,
        rating: 4.9,
        totalRatings: 342,
        enrolledStudents: 1234,
        totalDuration: const Duration(hours: 25),
        createdAt: DateTime.now().subtract(const Duration(days: 60)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '3',
        title: 'رؤية الحاسوب والتعلم العميق',
        description: 'تعلم كيفية بناء أنظمة رؤية الحاسوب باستخدام الشبكات العصبية العميقة.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=3',
        instructorId: '3',
        instructorName: 'م. خالد عبدالله',
        instructorBio: 'مهندس ذكاء اصطناعي في شركة تقنية رائدة',
        level: 'متوسط',
        category: 'رؤية الحاسوب',
        isEnrolled: true,
        objectives: [
          'فهم CNN و شبكات التصنيف',
          'بناء أنظمة كشف الأجسام',
          'تطبيقات عملية في الصور والفيديو',
        ],
        requirements: ['معرفة بـ Python', 'أساسيات تعلم الآلة'],
        modules: [],
        price: 199,
        rating: 4.7,
        totalRatings: 567,
        enrolledStudents: 2341,
        totalDuration: const Duration(hours: 18),
        createdAt: DateTime.now().subtract(const Duration(days: 45)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '4',
        title: 'Python للذكاء الاصطناعي - مجاني',
        description: 'تعلم برمجة Python من الصفر مع التركيز على تطبيقات الذكاء الاصطناعي.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=4',
        instructorId: '1',
        instructorName: 'د. أحمد محمد',
        instructorBio: 'خبير في مجال الذكاء الاصطناعي مع خبرة 10 سنوات',
        level: 'مبتدئ',
        category: 'البرمجة',
        objectives: [
          'أساسيات لغة Python',
          'المكتبات الأساسية للذكاء الاصطناعي',
          'بناء مشاريع عملية',
        ],
        requirements: ['لا توجد متطلبات سابقة'],
        modules: [],
        price: 0,
        rating: 4.6,
        totalRatings: 892,
        enrolledStudents: 8765,
        totalDuration: const Duration(hours: 15),
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
        updatedAt: DateTime.now(),
        isFree: true,
      ),
      CourseModel(
        id: '5',
        title: 'الذكاء الاصطناعي التوليدي وChatGPT',
        description: 'اكتشف عالم الذكاء الاصطناعي التوليدي وتعلم كيفية استخدام ChatGPT.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=5',
        instructorId: '2',
        instructorName: 'د. سارة أحمد',
        instructorBio: 'باحثة في مجال NLP مع خبرة 8 سنوات',
        level: 'متوسط',
        category: 'الذكاء التوليدي',
        isEnrolled: true,
        objectives: [
          'فهم تقنيات GPT وLLMs',
          'بناء تطبيقات باستخدام APIs',
          'Prompt Engineering احترافي',
        ],
        requirements: ['معرفة أساسية بالبرمجة'],
        modules: [],
        price: 149,
        rating: 4.9,
        totalRatings: 623,
        enrolledStudents: 3421,
        totalDuration: const Duration(hours: 10),
        createdAt: DateTime.now().subtract(const Duration(days: 10)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '6',
        title: 'بناء تطبيقات الذكاء الاصطناعي بـ TensorFlow',
        description: 'دورة عملية متقدمة لبناء وتدريب نماذج الذكاء الاصطناعي.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=6',
        instructorId: '3',
        instructorName: 'م. خالد عبدالله',
        instructorBio: 'مهندس ذكاء اصطناعي في شركة تقنية رائدة',
        level: 'متقدم',
        category: 'التعلم العميق',
        objectives: [
          'إتقان TensorFlow و Keras',
          'بناء نماذج متقدمة',
          'نشر النماذج في الإنتاج',
        ],
        requirements: ['خبرة في Python', 'معرفة بأساسيات ML'],
        modules: [],
        price: 399,
        rating: 4.8,
        totalRatings: 234,
        enrolledStudents: 876,
        totalDuration: const Duration(hours: 30),
        createdAt: DateTime.now().subtract(const Duration(days: 15)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '7',
        title: 'مقدمة في علم البيانات - مجاني',
        description: 'ابدأ رحلتك في علم البيانات مع هذه الدورة المجانية الشاملة.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=7',
        instructorId: '1',
        instructorName: 'د. أحمد محمد',
        instructorBio: 'خبير في مجال الذكاء الاصطناعي مع خبرة 10 سنوات',
        level: 'مبتدئ',
        category: 'علم البيانات',
        objectives: [
          'أساسيات تحليل البيانات',
          'التصور باستخدام Python',
          'الإحصاء الوصفي والاستدلالي',
        ],
        requirements: ['معرفة أساسية بالرياضيات'],
        modules: [],
        price: 0,
        rating: 4.5,
        totalRatings: 1567,
        enrolledStudents: 12345,
        totalDuration: const Duration(hours: 20),
        createdAt: DateTime.now().subtract(const Duration(days: 40)),
        updatedAt: DateTime.now(),
        isFree: true,
      ),
      CourseModel(
        id: '8',
        title: 'الذكاء الاصطناعي في الأعمال',
        description: 'تعلم كيفية تطبيق الذكاء الاصطناعي في بيئة الأعمال.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=8',
        instructorId: '2',
        instructorName: 'د. سارة أحمد',
        instructorBio: 'باحثة في مجال NLP مع خبرة 8 سنوات',
        level: 'متوسط',
        category: 'الأعمال',
        objectives: [
          'استراتيجيات AI للأعمال',
          'أتمتة العمليات',
          'تحليل البيانات للقرارات',
        ],
        requirements: ['خبرة في مجال الأعمال'],
        modules: [],
        price: 249,
        rating: 4.7,
        totalRatings: 432,
        enrolledStudents: 2134,
        totalDuration: const Duration(hours: 12),
        createdAt: DateTime.now().subtract(const Duration(days: 25)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '9',
        title: 'رؤية الحاسوب المتقدمة',
        description: 'تعلم تقنيات رؤية الحاسوب المتقدمة وتحليل الصور باستخدام Deep Learning.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=9',
        instructorId: '3',
        instructorName: 'م. خالد عبدالله',
        instructorBio: 'مهندس ذكاء اصطناعي في شركة تقنية رائدة',
        level: 'متقدم',
        category: 'رؤية الحاسوب',
        objectives: [
          'تقنيات CNN المتقدمة',
          'كشف الأشياء والتعرف عليها',
          'معالجة الفيديو والحركة',
        ],
        requirements: ['خبرة في Python', 'أساسيات رؤية الحاسوب'],
        modules: [],
        price: 449,
        rating: 4.9,
        totalRatings: 156,
        enrolledStudents: 543,
        totalDuration: const Duration(hours: 25),
        createdAt: DateTime.now().subtract(const Duration(days: 12)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '10',
        title: 'أساسيات برمجة الويب - مجاني',
        description: 'تعلم بناء مواقع الويب من الصفر باستخدام HTML, CSS, و JavaScript.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=10',
        instructorId: '1',
        instructorName: 'د. أحمد محمد',
        instructorBio: 'خبير في مجال الذكاء الاصطناعي مع خبرة 10 سنوات',
        level: 'مبتدئ',
        category: 'البرمجة',
        objectives: [
          'أساسيات HTML و CSS',
          'برمجة JavaScript التفاعلية',
          'بناء موقع متكامل',
        ],
        requirements: ['لا توجد متطلبات سابقة'],
        modules: [],
        price: 0,
        rating: 4.3,
        totalRatings: 2134,
        enrolledStudents: 15678,
        totalDuration: const Duration(hours: 18),
        createdAt: DateTime.now().subtract(const Duration(days: 60)),
        updatedAt: DateTime.now(),
        isFree: true,
      ),
      CourseModel(
        id: '11',
        title: 'إدارة المشاريع التقنية',
        description: 'تعلم أساليب إدارة المشاريع التقنية وقيادة فرق التطوير.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=11',
        instructorId: '2',
        instructorName: 'د. سارة أحمد',
        instructorBio: 'باحثة في مجال NLP مع خبرة 8 سنوات',
        level: 'متوسط',
        category: 'الأعمال',
        objectives: [
          'منهجيات Agile و Scrum',
          'إدارة الفرق التقنية',
          'تخطيط وتنفيذ المشاريع',
        ],
        requirements: ['خبرة في مجال التقنية'],
        modules: [],
        price: 199,
        rating: 4.6,
        totalRatings: 678,
        enrolledStudents: 3456,
        totalDuration: const Duration(hours: 14),
        createdAt: DateTime.now().subtract(const Duration(days: 18)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '12',
        title: 'تحليل البيانات الضخمة',
        description: 'اكتشف عالم البيانات الضخمة وتعلم تحليلها باستخدام أدوات متقدمة.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=12',
        instructorId: '3',
        instructorName: 'م. خالد عبدالله',
        instructorBio: 'مهندس ذكاء اصطناعي في شركة تقنية رائدة',
        level: 'متقدم',
        category: 'علم البيانات',
        objectives: [
          'تقنيات Big Data',
          'استخدام Hadoop و Spark',
          'تحليل البيانات الضخمة',
        ],
        requirements: ['خبرة في Python', 'أساسيات قواعد البيانات'],
        modules: [],
        price: 549,
        rating: 4.8,
        totalRatings: 289,
        enrolledStudents: 1234,
        totalDuration: const Duration(hours: 32),
        createdAt: DateTime.now().subtract(const Duration(days: 8)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '13',
        title: 'البرمجة بـ Flutter للمبتدئين - مجاني',
        description: 'تعلم تطوير تطبيقات الهاتف المحمول باستخدام Flutter من Google.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=13',
        instructorId: '1',
        instructorName: 'د. أحمد محمد',
        instructorBio: 'خبير في مجال الذكاء الاصطناعي مع خبرة 10 سنوات',
        level: 'مبتدئ',
        category: 'البرمجة',
        objectives: [
          'أساسيات Dart و Flutter',
          'بناء واجهات المستخدم',
          'نشر التطبيقات',
        ],
        requirements: ['معرفة أساسية بالبرمجة'],
        modules: [],
        price: 0,
        rating: 4.7,
        totalRatings: 1876,
        enrolledStudents: 9876,
        totalDuration: const Duration(hours: 22),
        createdAt: DateTime.now().subtract(const Duration(days: 35)),
        updatedAt: DateTime.now(),
        isFree: true,
      ),
      CourseModel(
        id: '14',
        title: 'تطوير APIs باستخدام Node.js',
        description: 'تعلم بناء واجهات برمجة التطبيقات القوية باستخدام Node.js و Express.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=14',
        instructorId: '2',
        instructorName: 'د. سارة أحمد',
        instructorBio: 'باحثة في مجال NLP مع خبرة 8 سنوات',
        level: 'متوسط',
        category: 'البرمجة',
        objectives: [
          'إتقان Node.js و Express',
          'تصميم RESTful APIs',
          'أمان واختبار APIs',
        ],
        requirements: ['معرفة JavaScript', 'أساسيات قواعد البيانات'],
        modules: [],
        price: 299,
        rating: 4.5,
        totalRatings: 543,
        enrolledStudents: 2765,
        totalDuration: const Duration(hours: 16),
        createdAt: DateTime.now().subtract(const Duration(days: 22)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '15',
        title: 'شبكات الحاسوب والأمن السيبراني',
        description: 'تعلم أساسيات الشبكات وحماية الأنظمة من التهديدات السيبرانية.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=15',
        instructorId: '3',
        instructorName: 'م. خالد عبدالله',
        instructorBio: 'مهندس ذكاء اصطناعي في شركة تقنية رائدة',
        level: 'متوسط',
        category: 'البرمجة',
        objectives: [
          'فهم بروتوكولات الشبكات',
          'تأمين الأنظمة والشبكات',
          'اكتشاف التهديدات',
        ],
        requirements: ['معرفة أساسية بأنظمة التشغيل'],
        modules: [],
        price: 349,
        rating: 4.6,
        totalRatings: 445,
        enrolledStudents: 1987,
        totalDuration: const Duration(hours: 20),
        createdAt: DateTime.now().subtract(const Duration(days: 14)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '16',
        title: 'تطوير الألعاب بـ Unity - مجاني',
        description: 'ابدأ رحلتك في تطوير الألعاب باستخدام محرك Unity المشهور.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=16',
        instructorId: '1',
        instructorName: 'د. أحمد محمد',
        instructorBio: 'خبير في مجال الذكاء الاصطناعي مع خبرة 10 سنوات',
        level: 'مبتدئ',
        category: 'البرمجة',
        objectives: [
          'أساسيات محرك Unity',
          'برمجة C# للألعاب',
          'إنشاء لعبة متكاملة',
        ],
        requirements: ['لا توجد متطلبات سابقة'],
        modules: [],
        price: 0,
        rating: 4.4,
        totalRatings: 1234,
        enrolledStudents: 8765,
        totalDuration: const Duration(hours: 25),
        createdAt: DateTime.now().subtract(const Duration(days: 30)),
        updatedAt: DateTime.now(),
        isFree: true,
      ),
      CourseModel(
        id: '17',
        title: 'الحوسبة السحابية مع AWS',
        description: 'تعلم كيفية استخدام خدمات أمازون السحابية لبناء تطبيقات قابلة للتوسع.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=17',
        instructorId: '2',
        instructorName: 'د. سارة أحمد',
        instructorBio: 'باحثة في مجال NLP مع خبرة 8 سنوات',
        level: 'متقدم',
        category: 'البرمجة',
        objectives: [
          'خدمات AWS الأساسية',
          'نشر التطبيقات السحابية',
          'أمان السحابة',
        ],
        requirements: ['خبرة في البرمجة', 'معرفة بالشبكات'],
        modules: [],
        price: 449,
        rating: 4.8,
        totalRatings: 322,
        enrolledStudents: 1543,
        totalDuration: const Duration(hours: 28),
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '18',
        title: 'أساسيات الذكاء الاصطناعي - مجاني',
        description: 'مقدمة شاملة لعالم الذكاء الاصطناعي وتطبيقاته المختلفة.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=18',
        instructorId: '3',
        instructorName: 'م. خالد عبدالله',
        instructorBio: 'مهندس ذكاء اصطناعي في شركة تقنية رائدة',
        level: 'مبتدئ',
        category: 'تعلم الآلة',
        objectives: [
          'مفاهيم الذكاء الاصطناعي',
          'أنواع التعلم الآلي',
          'تطبيقات عملية',
        ],
        requirements: ['معرفة أساسية بالرياضيات'],
        modules: [],
        price: 0,
        rating: 4.7,
        totalRatings: 2134,
        enrolledStudents: 15432,
        totalDuration: const Duration(hours: 16),
        createdAt: DateTime.now().subtract(const Duration(days: 45)),
        updatedAt: DateTime.now(),
        isFree: true,
      ),
      CourseModel(
        id: '19',
        title: 'التحليل الإحصائي المتقدم',
        description: 'دورة متقدمة في الإحصاء التطبيقي وتحليل البيانات المعقدة.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=19',
        instructorId: '1',
        instructorName: 'د. أحمد محمد',
        instructorBio: 'خبير في مجال الذكاء الاصطناعي مع خبرة 10 سنوات',
        level: 'متقدم',
        category: 'علم البيانات',
        objectives: [
          'النمذجة الإحصائية المتقدمة',
          'اختبارات الفرضيات',
          'تحليل الانحدار المعقد',
        ],
        requirements: ['معرفة قوية بالإحصاء', 'خبرة في R أو Python'],
        modules: [],
        price: 399,
        rating: 4.9,
        totalRatings: 234,
        enrolledStudents: 876,
        totalDuration: const Duration(hours: 24),
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '20',
        title: 'التسويق الرقمي والبيانات',
        description: 'تعلم كيفية استخدام البيانات في اتخاذ قرارات التسويق الذكية.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=20',
        instructorId: '2',
        instructorName: 'د. سارة أحمد',
        instructorBio: 'باحثة في مجال NLP مع خبرة 8 سنوات',
        level: 'متوسط',
        category: 'الأعمال',
        objectives: [
          'استراتيجيات التسويق المبنية على البيانات',
          'تحليل سلوك المستهلك',
          'أتمتة التسويق',
        ],
        requirements: ['معرفة أساسية بالتسويق'],
        modules: [],
        price: 199,
        rating: 4.5,
        totalRatings: 567,
        enrolledStudents: 3421,
        totalDuration: const Duration(hours: 14),
        createdAt: DateTime.now().subtract(const Duration(days: 16)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '21',
        title: 'ريادة الأعمال التقنية - مجاني',
        description: 'تعلم كيفية بناء شركة تقنية ناجحة من الصفر.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=21',
        instructorId: '3',
        instructorName: 'م. خالد عبدالله',
        instructorBio: 'مهندس ذكاء اصطناعي في شركة تقنية رائدة',
        level: 'مبتدئ',
        category: 'الأعمال',
        objectives: [
          'أساسيات ريادة الأعمال',
          'تطوير نماذج الأعمال',
          'جذب الاستثمار',
        ],
        requirements: ['شغف بالأعمال والتقنية'],
        modules: [],
        price: 0,
        rating: 4.6,
        totalRatings: 1876,
        enrolledStudents: 12345,
        totalDuration: const Duration(hours: 18),
        createdAt: DateTime.now().subtract(const Duration(days: 25)),
        updatedAt: DateTime.now(),
        isFree: true,
      ),
      CourseModel(
        id: '22',
        title: 'الروبوتات والأتمتة الذكية',
        description: 'اكتشف عالم الروبوتات وتقنيات الأتمتة الحديثة.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=22',
        instructorId: '1',
        instructorName: 'د. أحمد محمد',
        instructorBio: 'خبير في مجال الذكاء الاصطناعي مع خبرة 10 سنوات',
        level: 'متقدم',
        category: 'تعلم الآلة',
        objectives: [
          'أساسيات الروبوتات',
          'خوارزميات التحكم',
          'ROS وبرمجة الروبوتات',
        ],
        requirements: ['معرفة بالبرمجة', 'أساسيات الهندسة'],
        modules: [],
        price: 549,
        rating: 4.8,
        totalRatings: 123,
        enrolledStudents: 456,
        totalDuration: const Duration(hours: 32),
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '23',
        title: 'معالجة الإشارات الرقمية',
        description: 'تعلم تحليل ومعالجة الإشارات الرقمية للتطبيقات الحديثة.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=23',
        instructorId: '2',
        instructorName: 'د. سارة أحمد',
        instructorBio: 'باحثة في مجال NLP مع خبرة 8 سنوات',
        level: 'متقدم',
        category: 'معالجة اللغات',
        objectives: [
          'نظرية الإشارات',
          'المرشحات الرقمية',
          'معالجة الصوت والصورة',
        ],
        requirements: ['معرفة قوية بالرياضيات', 'أساسيات البرمجة'],
        modules: [],
        price: 449,
        rating: 4.7,
        totalRatings: 189,
        enrolledStudents: 678,
        totalDuration: const Duration(hours: 26),
        createdAt: DateTime.now().subtract(const Duration(days: 12)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '24',
        title: 'التطبيقات المحمولة الذكية - مجاني',
        description: 'بناء تطبيقات محمولة تستخدم تقنيات الذكاء الاصطناعي.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=24',
        instructorId: '3',
        instructorName: 'م. خالد عبدالله',
        instructorBio: 'مهندس ذكاء اصطناعي في شركة تقنية رائدة',
        level: 'متوسط',
        category: 'البرمجة',
        objectives: [
          'دمج AI في التطبيقات',
          'استخدام ML APIs',
          'تحسين الأداء',
        ],
        requirements: ['معرفة بتطوير التطبيقات', 'أساسيات AI'],
        modules: [],
        price: 0,
        rating: 4.5,
        totalRatings: 987,
        enrolledStudents: 5432,
        totalDuration: const Duration(hours: 20),
        createdAt: DateTime.now().subtract(const Duration(days: 18)),
        updatedAt: DateTime.now(),
        isFree: true,
      ),
      CourseModel(
        id: '25',
        title: 'الأمن السيبراني المتقدم',
        description: 'دورة شاملة في الأمن السيبراني والحماية من التهديدات المعقدة.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=25',
        instructorId: '1',
        instructorName: 'د. أحمد محمد',
        instructorBio: 'خبير في مجال الذكاء الاصطناعي مع خبرة 10 سنوات',
        level: 'متقدم',
        category: 'البرمجة',
        objectives: [
          'تقنيات الاختراق الأخلاقي',
          'تحليل البرمجيات الخبيثة',
          'أمان الشبكات المتقدم',
        ],
        requirements: ['خبرة في الشبكات', 'معرفة بأنظمة التشغيل'],
        modules: [],
        price: 649,
        rating: 4.9,
        totalRatings: 167,
        enrolledStudents: 543,
        totalDuration: const Duration(hours: 35),
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '26',
        title: 'تصميم واجهات المستخدم',
        description: 'تعلم أسس تصميم UI/UX لإنشاء تجارب مستخدم مميزة.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=26',
        instructorId: '2',
        instructorName: 'د. سارة أحمد',
        instructorBio: 'باحثة في مجال NLP مع خبرة 8 سنوات',
        level: 'متوسط',
        category: 'البرمجة',
        objectives: [
          'مبادئ تصميم UI/UX',
          'أدوات التصميم الحديثة',
          'اختبار تجربة المستخدم',
        ],
        requirements: ['حس فني', 'معرفة أساسية بالتقنية'],
        modules: [],
        price: 249,
        rating: 4.6,
        totalRatings: 678,
        enrolledStudents: 2987,
        totalDuration: const Duration(hours: 16),
        createdAt: DateTime.now().subtract(const Duration(days: 21)),
        updatedAt: DateTime.now(),
      ),
      CourseModel(
        id: '27',
        title: 'البرمجة كائنية التوجه - مجاني',
        description: 'أساسيات البرمجة كائنية التوجه باستخدام Java و Python.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=27',
        instructorId: '3',
        instructorName: 'م. خالد عبدالله',
        instructorBio: 'مهندس ذكاء اصطناعي في شركة تقنية رائدة',
        level: 'مبتدئ',
        category: 'البرمجة',
        objectives: [
          'مفاهيم OOP الأساسية',
          'الوراثة والتغليف',
          'التطبيق العملي',
        ],
        requirements: ['معرفة أساسية بالبرمجة'],
        modules: [],
        price: 0,
        rating: 4.4,
        totalRatings: 1543,
        enrolledStudents: 11234,
        totalDuration: const Duration(hours: 22),
        createdAt: DateTime.now().subtract(const Duration(days: 40)),
        updatedAt: DateTime.now(),
        isFree: true,
      ),
      CourseModel(
        id: '28',
        title: 'التمويل التقني والعملات الرقمية',
        description: 'فهم عالم العملات الرقمية والتقنيات المالية الحديثة.',
        thumbnailUrl: 'https://picsum.photos/400/225?random=28',
        instructorId: '1',
        instructorName: 'د. أحمد محمد',
        instructorBio: 'خبير في مجال الذكاء الاصطناعي مع خبرة 10 سنوات',
        level: 'متوسط',
        category: 'الأعمال',
        objectives: [
          'تقنية البلوك تشين',
          'العملات الرقمية',
          'الاستثمار التقني',
        ],
        requirements: ['معرفة أساسية بالتمويل'],
        modules: [],
        price: 349,
        rating: 4.3,
        totalRatings: 456,
        enrolledStudents: 1876,
        totalDuration: const Duration(hours: 18),
        createdAt: DateTime.now().subtract(const Duration(days: 28)),
        updatedAt: DateTime.now(),
      ),
    ];
  }
}