import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  
  AppLocalizations(this.locale);
  
  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }
  
  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();
  
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appTitle': 'Raqim - AI Platform',
      'home': 'Home',
      'courses': 'Courses',
      'community': 'Community',
      'news': 'News',
      'profile': 'Profile',
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'darkMode': 'Dark Mode',
      'lightMode': 'Light Mode',
      'arabic': 'Arabic',
      'english': 'English',
      'logout': 'Logout',
      'login': 'Login',
      'register': 'Register',
      'welcome': 'Welcome',
      'welcomeBack': 'Welcome back',
      'email': 'Email',
      'password': 'Password',
      'forgotPassword': 'Forgot Password?',
      'forgotPasswordDescription': "Don't worry! Enter your email and we'll send you a verification code to reset your password",
      'rememberedPassword': 'Remembered password?',
      'passwordRecovery': 'Password Recovery',
      'passwordRecoveryHelp': 'We will help you recover your account with simple and secure steps',
      'enterRegisteredEmail': 'Enter your registered email and we will send you a verification code',
      'dontHaveAccount': "Don't have an account?",
      'alreadyHaveAccount': 'Already have an account?',
      'enrolledCourses': 'Enrolled Courses',
      'completedCourses': 'Completed Courses',
      'certificates': 'Certificates',
      'points': 'Points',
      'badges': 'Badges',
      'recentActivities': 'Recent Activities',
      'statistics': 'Statistics',
      'readyToLearn': 'Ready to learn something new today?',
      'changeLanguage': 'Change Language',
      'changeTheme': 'Change Theme',
      'systemTheme': 'System Theme',
      'notifications': 'Notifications',
      'editProfile': 'Edit Profile',
      'user': 'User',
      'yourPlatformForAI': 'Your first Arabic platform\nfor Artificial Intelligence',
      'learnCreateExcel': 'Learn • Create • Excel',
      'loginToYourAccount': 'Login to your account',
      'createNewAccount': 'Create a new account',
      'getStarted': 'Get started',
      'continueWithGoogle': 'Continue with Google',
      'or': 'or',
      'name': 'Name',
      'confirmPassword': 'Confirm Password',
      'rememberMe': 'Remember me',
      'agreeToTerms': 'I agree to the Terms and Conditions',
      'alreadyHaveAccount': 'Already have an account?',
      'enterYourEmail': 'Enter your email',
      'weWillSendCode': 'We will send you a verification code',
      'sendCode': 'Send Code',
      'backToLogin': 'Back to Login',
      'verifyYourEmail': 'Verify your email',
      'verifyEmail': 'Email Verification',
      'createNewPassword': 'Create New Password',
      'newPasswordDifferent': 'Your new password must be different from previously used passwords',
      'newPassword': 'New Password',
      'enterStrongPassword': 'Enter a strong password',
      'confirmPassword': 'Confirm Password',
      'reEnterPassword': 'Re-enter your password',
      'passwordRequirements': 'Password Requirements:',
      'atLeast8Characters': 'At least 8 characters',
      'atLeastOneUppercase': 'At least one uppercase letter',
      'atLeastOneLowercase': 'At least one lowercase letter',
      'atLeastOneNumber': 'At least one number',
      'passwordsDoNotMatch': 'Passwords do not match',
      'passwordRequired': 'Password is required',
      'passwordTooShort': 'Password must be at least 8 characters',
      'passwordNeedsUppercase': 'Must contain at least one uppercase letter',
      'passwordNeedsLowercase': 'Must contain at least one lowercase letter',
      'passwordNeedsNumber': 'Must contain at least one number',
      'resetPassword': 'Reset Password',
      'passwordChangedSuccessfully': 'Password changed successfully!',
      'redirectingToLogin': 'Redirecting to login page...',
      'lastStep': 'Last Step',
      'oneStepAway': 'You are one step away from recovering your account\nCreate a new strong password',
      'myCertificates': 'My Certificates',
      'myCourses': 'My Courses',
      'specialOffers': 'Special Offers',
      'seeAll': 'See All',
      'categories': 'Categories',
      'recommendedForYou': 'Recommended For You',
      'searchCourses': 'Search courses...',
      'programming': 'Programming',
      'design': 'Design',
      'business': 'Business',
      'languages': 'Languages',
      'exploreCourses': 'Explore Courses',
      'quickActions': 'Quick Actions',
      'noCertificatesYet': 'No certificates yet',
      'completeCoursesCertificates': 'Complete courses to earn certificates',
      'certificateNumber': 'Certificate Number',
      'issueDate': 'Issue Date',
      'finalGrade': 'Final Grade',
      'download': 'Download',
      'share': 'Share',
      'certificateDetails': 'Certificate Details',
      'studentName': 'Student Name',
      'instructorName': 'Instructor Name',
      'courseDuration': 'Course Duration',
      'totalHours': 'Total Hours',
      'completionDate': 'Completion Date',
      'close': 'Close',
      'instructor': 'Instructor',
      'duration': 'Duration',
      'lessons': 'Lessons',
      'lesson': 'Lesson',
      'hours': 'Hours',
      'hour': 'Hour',
      'minutes': 'Minutes',
      'students': 'Students',
      'student': 'Student',
      'level': 'Level',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'rating': 'Rating',
      'reviews': 'Reviews',
      'price': 'Price',
      'free': 'Free',
      'sar': 'SAR',
      'enrollNow': 'Enroll Now',
      'buyNow': 'Buy Now',
      'enrollNowFree': 'Enroll Now - Free',
      'continueLeaming': 'Continue Learning',
      'rewatch': 'Rewatch',
      'viewCertificate': 'View Certificate',
      'progress': 'Progress',
      'completed': 'Completed',
      'completedStatus': 'Completed',
      'inProgress': 'In Progress',
      'notStarted': 'Not Started',
      'all': 'All',
      'quizzes': 'Quizzes',
      'quiz': 'Quiz',
      'assignment': 'Assignment',
      'assignments': 'Assignments',
      'enrolledInCourse': 'Enrolled in Course',
      'studentsEnrolled': 'Students Enrolled',
      'enrolledSuccessfully': 'Enrolled Successfully',
      'startLearning': 'Start Learning',
      'continueCourse': 'Continue Course',
      'courseDetails': 'Course Details',
      'whatYouWillLearn': 'What You Will Learn',
      'requirements': 'Requirements',
      'description': 'Description',
      'curriculum': 'Curriculum',
      'aboutInstructor': 'About Instructor',
      'enterCodeSentTo': 'Enter the code sent to',
      'enterOtpCode': 'Enter the 6-digit verification code sent to',
      'pleaseEnterFullCode': 'Please enter the full verification code',
      'codeSentAgain': 'Verification code sent again',
      'verifyCode': 'Verify Code',
      'didntReceiveCode': "Didn't receive code?",
      'resend': 'Resend',
      'verify': 'Verify',
      'identityVerification': 'Identity Verification',
      'identityVerificationDesc': 'We need to verify that you are the account owner\nEnter the verification code sent to your email',
      'enterVerificationCode': 'Enter Verification Code',
      'weSentCodeTo': 'We sent a verification code to',
      'resetYourPassword': 'Reset your password',
      'enterNewPassword': 'Enter your new password',
      'resetPassword': 'Reset Password',
      'paymentMethods': 'Payment Methods',
      'choosePaymentMethod': 'Choose your payment method',
      'creditCard': 'Credit Card',
      'paypal': 'PayPal',
      'applePay': 'Apple Pay',
      'googlePay': 'Google Pay',
      'paymentDetails': 'Payment Details',
      'cardNumber': 'Card Number',
      'cardHolderName': 'Card Holder Name',
      'expiryDate': 'Expiry Date',
      'cvv': 'CVV',
      'pay': 'Pay',
      'paymentSuccessful': 'Payment Successful',
      'enrollmentSuccess': 'You have successfully enrolled in',
      'startLearning': 'Start Learning',
      'paymentHistory': 'Payment History',
      'transactionDetails': 'Transaction Details',
      'continueToPayment': 'Continue to Payment',
      'purchaseDetails': 'Purchase Details',
      'taxIncluded': 'Tax Included',
      'recommended': 'Recommended',
      'securePayments': 'All transactions are secure and encrypted with SSL technology',
      'enrolledSuccessfully': 'Successfully enrolled in the free course!',
      'enrollNowFree': 'Enroll Now for Free',
      'buyNow': 'Buy Now',
      'emailRequired': 'Email is required',
      'enterValidEmail': 'Enter a valid email',
      'passwordRequired': 'Password is required',
      'passwordMinLength': 'Password must be at least 6 characters',
      'continueWith': 'Continue with',
      'noAccount': "Don't have an account?",
      'createAccount': 'Create Account',
      'mustAgreeToTerms': 'You must agree to the terms and conditions',
      'joinUsAndStart': 'Join us and start your learning journey',
      'fullName': 'Full Name',
      'nameRequired': 'Name is required',
      'nameMinLength': 'Name must be at least 3 characters',
      'confirmPasswordRequired': 'Confirm password is required',
      'passwordMismatch': 'Passwords do not match',
      'agreeToTermsAndConditions': 'I agree to the',
      'termsAndConditions': 'Terms and Conditions',
      'and': 'and',
      'privacyPolicy': 'Privacy Policy',
      'registerWithGoogle': 'Register with Google',
      'createAccount': 'Create Account',
      // Activities
      'watchedLesson': 'Watched lesson',
      'commentedOnPost': 'Commented on post in community', 
      'introToMachineLearning': 'Introduction to Machine Learning',
      'sinceHour': '1 hour ago',
      'sinceHours': 'hours ago',
      'since': 'since',
      // Time
      'hourAgo': 'hour ago',
      'hoursAgo': 'hours ago',
      'dayAgo': 'day ago',
      'daysAgo': 'days ago',
      'minuteAgo': 'minute ago',
      'minutesAgo': 'minutes ago',
      // Profile
      'profileImageUpdated': 'Profile picture updated successfully',
      'errorOccurred': 'An error occurred',
      'chooseImageSource': 'Choose image source',
      'gallery': 'Gallery',
      'chooseFromGallery': 'Choose from gallery',
      'camera': 'Camera',
      'takeNewPhoto': 'Take a new photo',
      // Courses
      'coursesTitle': 'Educational Courses',
      'searchCourse': 'Search for a course...',
      'all': 'All',
      'machineLearning': 'Machine Learning',
      'naturalLanguageProcessing': 'Natural Language Processing',
      'computerVision': 'Computer Vision',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'free': 'Free',
      'sar': 'SAR',
      'retry': 'Retry',
      // Course titles and descriptions
      'mlForBeginnersTitle': 'Machine Learning Basics for Beginners',
      'mlForBeginnersDesc': 'Learn the fundamentals of AI and machine learning from scratch. Comprehensive course covering all basic concepts.',
      'nlpAdvancedTitle': 'Advanced Natural Language Processing',
      'nlpAdvancedDesc': 'Advanced course in natural language processing using the latest techniques and models.',
      'computerVisionTitle': 'Computer Vision and Deep Learning',
      'computerVisionDesc': 'Learn how to build computer vision systems using deep neural networks.',
      'pythonForAITitle': 'Python for AI - Free',
      'pythonForAIDesc': 'Learn Python programming from scratch with focus on AI applications. Free comprehensive course for beginners.',
      'generativeAITitle': 'Generative AI and ChatGPT',
      'generativeAIDesc': 'Explore the world of generative AI and learn how to use ChatGPT and modern AI tools.',
      'tensorflowAppsTitle': 'Building AI Apps with TensorFlow',
      'tensorflowAppsDesc': 'Advanced practical course for building and training AI models using TensorFlow and Keras.',
      'dataScIntroTitle': 'Introduction to Data Science - Free',
      'dataScIntroDesc': 'Start your data science journey with this free comprehensive course. Learn analysis, visualization and statistics.',
      'aiBusinessTitle': 'AI in Business',
      'aiBusinessDesc': 'Learn how to apply AI in business environment to increase productivity and improve decision making.',
      // Instructor names and bios
      'instructorAhmed': 'Dr. Ahmed Mohamed',
      'instructorAhmedBio': 'AI expert with 10 years of experience',
      'instructorSara': 'Dr. Sara Ahmed',
      'instructorSaraBio': 'NLP researcher with 8 years of experience',
      'instructorKhaled': 'Eng. Khaled Abdullah',
      'instructorKhaledBio': 'AI engineer at leading tech company',
      // Course objectives
      'understandMLBasics': 'Understand machine learning basics',
      'buildSimpleModels': 'Build simple models',
      'applyBasicAlgorithms': 'Apply basic algorithms',
      'understandAdvancedNLP': 'Understand advanced NLP models',
      'buildComplexApps': 'Build complex applications',
      'useTransformers': 'Use Transformers',
      'understandCNN': 'Understand CNN and classification networks',
      'buildDetectionSystems': 'Build object detection systems',
      'practicalImageVideo': 'Practical applications in images and video',
      'pythonBasics': 'Python language basics',
      'aiLibraries': 'Essential AI libraries',
      'buildPracticalProjects': 'Build practical projects',
      'understandGPT': 'Understand GPT and LLMs techniques',
      'buildWithAPIs': 'Build applications using APIs',
      'professionalPromptEng': 'Professional Prompt Engineering',
      'masterTensorflow': 'Master TensorFlow and Keras',
      'buildAdvancedModels': 'Build advanced models',
      'deployToProduction': 'Deploy models to production',
      'dataAnalysisBasics': 'Data analysis basics',
      'pythonVisualization': 'Visualization using Python',
      'descriptiveInferentialStats': 'Descriptive and inferential statistics',
      'aiBusinessStrategies': 'AI strategies for business',
      'processAutomation': 'Process automation',
      'dataAnalysisDecisions': 'Data analysis for decisions',
      // Requirements
      'basicProgramming': 'Basic programming knowledge',
      'desireToLearn': 'Desire to learn',
      'pythonExperience': 'Python experience',
      'nlpBasics': 'NLP basics knowledge',
      'mlBasics': 'Machine learning basics',
      'noRequirements': 'No prerequisites',
      'basicMath': 'Basic mathematics knowledge',
      'businessExperience': 'Business experience',
      // Community
      'communityTitle': 'Community',
      'recent': 'Recent',
      'popular': 'Most Popular',
      'comments': 'Comments',
      'now': 'Now',
      'vote': 'Vote',
      // Community post content
      'discussionTitle1': 'Best ML Algorithm for Beginners?',
      'discussionContent1': 'I am just starting to learn ML and confused about which algorithm to start with. Any suggestions?',
      'discussionTitle2': 'GPT-4 vs Claude: Performance Comparison',
      'discussionContent2': 'Has anyone done a detailed comparison between GPT-4 and Claude? I am interested in accuracy for Arabic text.',
      'discussionTitle3': 'Computer Vision Project Ideas',
      'discussionContent3': 'Looking for interesting CV project ideas for my portfolio. Preferably something related to Arabic OCR.',
      'discussionTitle4': 'Tips for NLP in Arabic',
      'discussionContent4': 'Working on an Arabic sentiment analysis project. Any tips or resources you would recommend?',
      // User names
      'userName1': 'Ahmed Ali',
      'userName2': 'Sara Mohamed',
      'userName3': 'Omar Hassan',
      'userName4': 'Fatima Ibrahim',
      // News
      'newsTitle': 'News',
      'newsAll': 'All',
      'newResearch': 'New Research',
      'productsApplications': 'Products & Applications',
      'investmentFunding': 'Investment & Funding',
      'aiEthics': 'AI Ethics',
      // News articles
      'newsArticle1Title': 'OpenAI Announces GPT-5: Revolutionary Language Model',
      'newsArticle1Description': 'OpenAI has unveiled GPT-5, featuring unprecedented capabilities in reasoning and multilingual understanding, particularly for Arabic.',
      'newsArticle2Title': 'Google DeepMind Breakthrough in Medical AI',
      'newsArticle2Description': 'New AI system achieves 95% accuracy in early cancer detection, promising to revolutionize healthcare diagnostics.',
      'newsArticle3Title': 'Meta Releases Open Source Arabic LLM',
      'newsArticle3Description': 'Meta new language model specifically trained on Arabic datasets shows superior performance in regional dialects.',
      'newsArticle4Title': 'AI Investment Reaches Record \$50 Billion',
      'newsArticle4Description': 'Venture capital funding in AI startups hits all-time high, with focus on emerging markets including MENA region.',
      'newsArticle5Title': 'New EU AI Regulation Guidelines Released',
      'newsArticle5Description': 'European Union publishes comprehensive framework for AI governance, setting global standards for ethical AI development.',
      // News sources
      'newsSource1': 'Tech Crunch',
      'newsSource2': 'MIT Technology Review',
      'newsSource3': 'AI News',
      'newsSource4': 'Reuters',
      'newsSource5': 'Nature AI',
      // Quick Actions
      'quickActions': 'Quick Actions',
      'exploreCourses': 'Explore Courses',
      'myCourses': 'My Courses',
      'myCertificates': 'My Certificates',
      // Course Details
      'courseProgress': 'Course Progress',
      'completed': 'Completed',
      'viewCertificate': 'View Certificate',
      'educationalObjectives': 'Educational Objectives',
      'requirements': 'Requirements',
      'enrolledInCourse': 'Enrolled in Course',
      'progress': 'Progress',
      'continueLeaming': 'Continue Learning',
      'rewatch': 'Rewatch',
      'studentsEnrolled': 'Students Enrolled',
      // My Courses
      'myCoursesTitle': 'My Courses',
      'inProgress': 'In Progress',
      'completedStatus': 'Completed',
      'noCoursesEnrolled': 'No courses enrolled yet',
      'noCoursesInProgress': 'No courses in progress',
      'noCoursesCompleted': 'No completed courses yet',
      'startLearningToday': 'Start your learning journey today',
      'browseCourses': 'Browse Courses',
      'continueButton': 'Continue',
      'getCertificate': 'Get Certificate',
      'lastAccessedOn': 'Last accessed on',
      'lessons': 'Lessons',
      'hours': 'Hours',
      'quizzes': 'Quizzes',
      'lesson': 'Lesson',
      'hour': 'Hour',
      'quiz': 'Quiz',
      // Certificates
      'certificatesTitle': 'My Certificates', 
      'noCertificatesYet': 'No certificates yet',
      'completeCourseToEarn': 'Complete courses to earn certificates',
      'certificateOf': 'Certificate of',
      'completion': 'Completion',
      'issuedOn': 'Issued on',
      'issuedDate': 'Issue Date',
      'certificateNumber': 'Certificate Number',
      'studentName': 'Student Name',
      'instructorName': 'Instructor',
      'level': 'Level',
      'totalHours': 'Total Hours',
      'finalGrade': 'Final Grade',
      'download': 'Download',
      'share': 'Share',
      'downloadingCertificate': 'Downloading certificate...',
      'certificateDownloaded': 'Certificate downloaded successfully',
      'shareCertificate': 'Share Certificate',
      'copyLink': 'Copy Link',
      'linkCopied': 'Link copied!',
      'downloadCertificate': 'Download Certificate',
      // Lesson Player
      'lessonPlayer': 'Lesson Player',
      'completeAndContinue': 'Complete & Continue',
      'nextLesson': 'Next Lesson',
      'previousLesson': 'Previous Lesson',
      'courseMaterials': 'Course Materials',
      'discussion': 'Discussion',
      'notes': 'Notes',
      'transcript': 'Transcript',
      // Community
      'createPost': 'Create Post',
      'whatsOnYourMind': 'What\'s on your mind?',
      'postTitle': 'Post Title',
      'postContent': 'Post Content',
      'publish': 'Publish',
      'cancel': 'Cancel',
      'writeComment': 'Write a comment...',
      'post': 'Post',
      'reply': 'Reply',
      'noComments': 'No comments yet',
      'beFirstToComment': 'Be the first to comment',
      'loadingComments': 'Loading comments...',
      'viewAllComments': 'View all comments',
      'hideComments': 'Hide comments',
      // Profile
      'editProfileTitle': 'Edit Profile',
      'bio': 'Bio',
      'location': 'Location',
      'website': 'Website',
      'save': 'Save',
      'profileUpdated': 'Profile updated successfully',
      'changeProfilePicture': 'Change Profile Picture',
      // Settings
      'settingsTitle': 'Settings',
      'accountSettings': 'Account Settings',
      'notificationSettings': 'Notification Settings',
      'privacySettings': 'Privacy Settings',
      'pushNotifications': 'Push Notifications',
      'emailNotifications': 'Email Notifications',
      'darkTheme': 'Dark Theme',
      'lightTheme': 'Light Theme',
      'systemDefault': 'System Default',
      'about': 'About',
      'version': 'Version',
      'termsOfService': 'Terms of Service',
      'helpSupport': 'Help & Support',
      // General
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'warning': 'Warning',
      'info': 'Info',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',
      'close': 'Close',
      'delete': 'Delete',
      'edit': 'Edit',
      'update': 'Update',
      'submit': 'Submit',
      'confirm': 'Confirm',
      'back': 'Back',
      'next': 'Next',
      'skip': 'Skip',
      'done': 'Done',
      'search': 'Search',
      'filter': 'Filter',
      'sort': 'Sort',
      'refresh': 'Refresh',
      'loadMore': 'Load More',
      'showLess': 'Show Less',
      'showMore': 'Show More',
      'seeAll': 'See All',
      'noData': 'No data available',
      'noResults': 'No results found',
      'tryAgain': 'Try Again',
      'somethingWentWrong': 'Something went wrong',
      'pleaseWait': 'Please wait...',
      'networkError': 'Network error. Please check your connection.',
      'sessionExpired': 'Session expired. Please login again.',
      'unauthorized': 'Unauthorized access',
      'pageNotFound': 'Page not found',
      'backToHome': 'Back to Home',
    },
    'ar': {
      'appTitle': 'رقيم - منصة الذكاء الاصطناعي',
      'home': 'الرئيسية',
      'courses': 'الدورات',
      'community': 'المجتمع',
      'news': 'الأخبار',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'theme': 'المظهر',
      'darkMode': 'الوضع الداكن',
      'lightMode': 'الوضع الفاتح',
      'arabic': 'العربية',
      'english': 'الإنجليزية',
      'logout': 'تسجيل الخروج',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'welcome': 'مرحباً',
      'welcomeBack': 'مرحباً بعودتك',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'forgotPasswordDescription': 'لا تقلق! أدخل بريدك الإلكتروني وسنرسل لك رمز التحقق لإعادة تعيين كلمة المرور',
      'rememberedPassword': 'تذكرت كلمة المرور؟',
      'passwordRecovery': 'استعادة كلمة المرور',
      'passwordRecoveryHelp': 'سنساعدك في استعادة حسابك بخطوات بسيطة وآمنة',
      'enterRegisteredEmail': 'أدخل بريدك الإلكتروني المسجل وسنرسل لك رمز التحقق',
      'dontHaveAccount': 'ليس لديك حساب؟',
      'alreadyHaveAccount': 'لديك حساب بالفعل؟',
      'enrolledCourses': 'الدورات المسجلة',
      'completedCourses': 'الدورات المكتملة',
      'certificates': 'الشهادات',
      'points': 'النقاط',
      'badges': 'الشارات',
      'recentActivities': 'الأنشطة الأخيرة',
      'statistics': 'الإحصائيات',
      'readyToLearn': 'مستعد لتعلم شيء جديد اليوم؟',
      'changeLanguage': 'تغيير اللغة',
      'changeTheme': 'تغيير المظهر',
      'systemTheme': 'مظهر النظام',
      'notifications': 'الإشعارات',
      'editProfile': 'تعديل الملف الشخصي',
      'user': 'المستخدم',
      'yourPlatformForAI': 'منصتك العربية الأولى\nللذكاء الاصطناعي',
      'learnCreateExcel': 'تعلم • ابتكر • تميز',
      'loginToYourAccount': 'سجل دخولك إلى حسابك',
      'createNewAccount': 'إنشاء حساب جديد',
      'getStarted': 'ابدأ رحلتك',
      'continueWithGoogle': 'المتابعة مع جوجل',
      'or': 'أو',
      'name': 'الاسم',
      'confirmPassword': 'تأكيد كلمة المرور',
      'rememberMe': 'تذكرني',
      'agreeToTerms': 'أوافق على الشروط والأحكام',
      'alreadyHaveAccount': 'لديك حساب بالفعل؟',
      'enterYourEmail': 'أدخل بريدك الإلكتروني',
      'weWillSendCode': 'سنرسل لك رمز التحقق',
      'sendCode': 'إرسال الرمز',
      'backToLogin': 'العودة لتسجيل الدخول',
      'verifyYourEmail': 'تحقق من بريدك الإلكتروني',
      'verifyEmail': 'التحقق من البريد الإلكتروني',
      'createNewPassword': 'إنشاء كلمة مرور جديدة',
      'newPasswordDifferent': 'كلمة المرور الجديدة يجب أن تكون مختلفة عن كلمات المرور السابقة',
      'newPassword': 'كلمة المرور الجديدة',
      'enterStrongPassword': 'أدخل كلمة مرور قوية',
      'confirmPassword': 'تأكيد كلمة المرور',
      'reEnterPassword': 'أعد إدخال كلمة المرور',
      'passwordRequirements': 'متطلبات كلمة المرور:',
      'atLeast8Characters': '8 أحرف على الأقل',
      'atLeastOneUppercase': 'حرف كبير واحد على الأقل',
      'atLeastOneLowercase': 'حرف صغير واحد على الأقل',
      'atLeastOneNumber': 'رقم واحد على الأقل',
      'passwordsDoNotMatch': 'كلمات المرور غير متطابقة',
      'passwordRequired': 'كلمة المرور مطلوبة',
      'passwordTooShort': 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
      'passwordNeedsUppercase': 'يجب أن تحتوي على حرف كبير واحد على الأقل',
      'passwordNeedsLowercase': 'يجب أن تحتوي على حرف صغير واحد على الأقل',
      'passwordNeedsNumber': 'يجب أن تحتوي على رقم واحد على الأقل',
      'resetPassword': 'إعادة تعيين كلمة المرور',
      'passwordChangedSuccessfully': 'تم تغيير كلمة المرور بنجاح!',
      'redirectingToLogin': 'جاري تحويلك إلى صفحة تسجيل الدخول...',
      'lastStep': 'الخطوة الأخيرة',
      'oneStepAway': 'أنت على بعد خطوة واحدة من استعادة حسابك\nأنشئ كلمة مرور جديدة وقوية',
      'myCertificates': 'شهاداتي',
      'myCourses': 'دوراتي',
      'specialOffers': 'عروض خاصة',
      'seeAll': 'عرض الكل',
      'categories': 'الفئات',
      'recommendedForYou': 'موصى به لك',
      'searchCourses': 'البحث عن دورات...',
      'programming': 'البرمجة',
      'design': 'التصميم',
      'business': 'الأعمال',
      'languages': 'اللغات',
      'exploreCourses': 'استكشف الدورات',
      'quickActions': 'إجراءات سريعة',
      'noCertificatesYet': 'لا توجد شهادات بعد',
      'completeCoursesCertificates': 'أكمل الدورات للحصول على شهادات',
      'certificateNumber': 'رقم الشهادة',
      'issueDate': 'تاريخ الإصدار',
      'finalGrade': 'الدرجة النهائية',
      'download': 'تحميل',
      'share': 'مشاركة',
      'certificateDetails': 'تفاصيل الشهادة',
      'studentName': 'اسم الطالب',
      'instructorName': 'اسم المدرس',
      'courseDuration': 'مدة الدورة',
      'totalHours': 'إجمالي الساعات',
      'completionDate': 'تاريخ الإتمام',
      'close': 'إغلاق',
      'instructor': 'المدرس',
      'duration': 'المدة',
      'lessons': 'دروس',
      'lesson': 'درس',
      'hours': 'ساعات',
      'hour': 'ساعة',
      'minutes': 'دقائق',
      'students': 'طلاب',
      'student': 'طالب',
      'level': 'المستوى',
      'beginner': 'مبتدئ',
      'intermediate': 'متوسط',
      'advanced': 'متقدم',
      'rating': 'التقييم',
      'reviews': 'مراجعات',
      'price': 'السعر',
      'free': 'مجاني',
      'sar': 'ريال',
      'enrollNow': 'سجل الآن',
      'buyNow': 'اشترِ الآن',
      'enrollNowFree': 'سجل الآن مجاناً',
      'continueLeaming': 'استمر في التعلم',
      'rewatch': 'إعادة المشاهدة',
      'viewCertificate': 'عرض الشهادة',
      'progress': 'التقدم',
      'completed': 'مكتمل',
      'completedStatus': 'مكتمل',
      'inProgress': 'قيد التقدم',
      'notStarted': 'لم يبدأ',
      'all': 'الكل',
      'quizzes': 'اختبارات',
      'quiz': 'اختبار',
      'assignment': 'واجب',
      'assignments': 'واجبات',
      'enrolledInCourse': 'مسجل في الدورة',
      'studentsEnrolled': 'طالب مسجل',
      'enrolledSuccessfully': 'تم التسجيل بنجاح',
      'startLearning': 'ابدأ التعلم',
      'continueCourse': 'استمر في الدورة',
      'courseDetails': 'تفاصيل الدورة',
      'whatYouWillLearn': 'ماذا ستتعلم',
      'requirements': 'المتطلبات',
      'description': 'الوصف',
      'curriculum': 'المنهج',
      'aboutInstructor': 'عن المدرس',
      'enterCodeSentTo': 'أدخل الرمز المرسل إلى',
      'enterOtpCode': 'أدخل رمز التحقق المكون من 6 أرقام المرسل إلى',
      'pleaseEnterFullCode': 'الرجاء إدخال رمز التحقق كاملاً',
      'codeSentAgain': 'تم إرسال رمز التحقق مرة أخرى',
      'verifyCode': 'تحقق من الرمز',
      'didntReceiveCode': 'لم تستلم الرمز؟',
      'resend': 'إعادة إرسال',
      'verify': 'تحقق',
      'identityVerification': 'التحقق من الهوية',
      'identityVerificationDesc': 'نحتاج للتأكد من أنك صاحب الحساب\nأدخل رمز التحقق المرسل إلى بريدك الإلكتروني',
      'enterVerificationCode': 'أدخل رمز التحقق',
      'weSentCodeTo': 'أرسلنا رمز التحقق إلى',
      'resetYourPassword': 'إعادة تعيين كلمة المرور',
      'enterNewPassword': 'أدخل كلمة المرور الجديدة',
      'resetPassword': 'إعادة تعيين',
      'paymentMethods': 'طرق الدفع',
      'choosePaymentMethod': 'اختر طريقة الدفع',
      'creditCard': 'بطاقة ائتمان',
      'paypal': 'باي بال',
      'applePay': 'آبل باي',
      'googlePay': 'جوجل باي',
      'paymentDetails': 'تفاصيل الدفع',
      'cardNumber': 'رقم البطاقة',
      'cardHolderName': 'اسم حامل البطاقة',
      'expiryDate': 'تاريخ الانتهاء',
      'cvv': 'رمز الأمان',
      'pay': 'ادفع',
      'paymentSuccessful': 'تم الدفع بنجاح',
      'enrollmentSuccess': 'لقد تم تسجيلك بنجاح في',
      'startLearning': 'ابدأ التعلم',
      'paymentHistory': 'سجل المدفوعات',
      'transactionDetails': 'تفاصيل المعاملة',
      'emailRequired': 'البريد الإلكتروني مطلوب',
      'enterValidEmail': 'أدخل بريد إلكتروني صحيح',
      'passwordRequired': 'كلمة المرور مطلوبة',
      'passwordMinLength': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'continueWith': 'المتابعة مع',
      'noAccount': 'ليس لديك حساب؟',
      'createAccount': 'إنشاء حساب',
      'mustAgreeToTerms': 'يجب الموافقة على الشروط والأحكام',
      'joinUsAndStart': 'انضم إلينا وابدأ رحلة التعلم',
      'fullName': 'الاسم الكامل',
      'nameRequired': 'الاسم مطلوب',
      'nameMinLength': 'الاسم يجب أن يكون 3 أحرف على الأقل',
      'confirmPasswordRequired': 'تأكيد كلمة المرور مطلوب',
      'passwordMismatch': 'كلمتا المرور غير متطابقتين',
      'agreeToTermsAndConditions': 'أوافق على ',
      'termsAndConditions': 'الشروط والأحكام',
      'and': ' و',
      'privacyPolicy': 'سياسة الخصوصية',
      'registerWithGoogle': 'التسجيل بواسطة Google',
      'continueToPayment': 'المتابعة للدفع',
      'purchaseDetails': 'تفاصيل الشراء',
      'taxIncluded': 'شامل الضريبة',
      'recommended': 'موصى به',
      'securePayments': 'جميع المعاملات آمنة ومشفرة بتقنية SSL',
      'enrolledSuccessfully': 'تم التسجيل في الدورة المجانية بنجاح!',
      'enrollNowFree': 'سجل الآن مجاناً',
      'buyNow': 'اشترِ الآن',
      // Activities
      'watchedLesson': 'شاهدت درس',
      'commentedOnPost': 'علقت على منشور في المجتمع',
      'introToMachineLearning': 'مقدمة في تعلم الآلة',
      'sinceHour': 'منذ ساعة',
      'sinceHours': 'ساعات',
      'since': 'منذ',
      // Time
      'hourAgo': 'ساعة',
      'hoursAgo': 'ساعات',
      'dayAgo': 'يوم',
      'daysAgo': 'أيام',
      'minuteAgo': 'دقيقة',
      'minutesAgo': 'دقائق',
      // Profile
      'profileImageUpdated': 'تم تحديث صورة الملف الشخصي بنجاح',
      'errorOccurred': 'حدث خطأ',
      'chooseImageSource': 'اختر مصدر الصورة',
      'gallery': 'المعرض',
      'chooseFromGallery': 'اختر صورة من معرض الصور',
      'camera': 'الكاميرا',
      'takeNewPhoto': 'التقط صورة جديدة',
      // Courses
      'coursesTitle': 'الدورات التعليمية',
      'searchCourse': 'ابحث عن دورة...',
      'all': 'الكل',
      'machineLearning': 'تعلم الآلة',
      'naturalLanguageProcessing': 'معالجة اللغات الطبيعية',
      'computerVision': 'رؤية الحاسوب',
      'beginner': 'مبتدئ',
      'intermediate': 'متوسط',
      'advanced': 'متقدم',
      'free': 'مجاني',
      'sar': 'ر.س',
      'retry': 'إعادة المحاولة',
      // Course titles and descriptions
      'mlForBeginnersTitle': 'أساسيات تعلم الآلة للمبتدئين',
      'mlForBeginnersDesc': 'تعلم أساسيات الذكاء الاصطناعي وتعلم الآلة من الصفر. دورة شاملة تغطي جميع المفاهيم الأساسية.',
      'nlpAdvancedTitle': 'معالجة اللغات الطبيعية المتقدمة',
      'nlpAdvancedDesc': 'دورة متقدمة في معالجة اللغات الطبيعية باستخدام أحدث التقنيات والنماذج.',
      'computerVisionTitle': 'رؤية الحاسوب والتعلم العميق',
      'computerVisionDesc': 'تعلم كيفية بناء أنظمة رؤية الحاسوب باستخدام الشبكات العصبية العميقة.',
      'pythonForAITitle': 'Python للذكاء الاصطناعي - مجاني',
      'pythonForAIDesc': 'تعلم برمجة Python من الصفر مع التركيز على تطبيقات الذكاء الاصطناعي. دورة مجانية شاملة للمبتدئين.',
      'generativeAITitle': 'الذكاء الاصطناعي التوليدي وChatGPT',
      'generativeAIDesc': 'اكتشف عالم الذكاء الاصطناعي التوليدي وتعلم كيفية استخدام ChatGPT وأدوات AI الحديثة.',
      'tensorflowAppsTitle': 'بناء تطبيقات الذكاء الاصطناعي بـ TensorFlow',
      'tensorflowAppsDesc': 'دورة عملية متقدمة لبناء وتدريب نماذج الذكاء الاصطناعي باستخدام TensorFlow و Keras.',
      'dataScIntroTitle': 'مقدمة في علم البيانات - مجاني',
      'dataScIntroDesc': 'ابدأ رحلتك في علم البيانات مع هذه الدورة المجانية الشاملة. تعلم التحليل والتصور والإحصاء.',
      'aiBusinessTitle': 'الذكاء الاصطناعي في الأعمال',
      'aiBusinessDesc': 'تعلم كيفية تطبيق الذكاء الاصطناعي في بيئة الأعمال وزيادة الإنتاجية وتحسين اتخاذ القرار.',
      // Instructor names and bios
      'instructorAhmed': 'د. أحمد محمد',
      'instructorAhmedBio': 'خبير في مجال الذكاء الاصطناعي مع خبرة 10 سنوات',
      'instructorSara': 'د. سارة أحمد',
      'instructorSaraBio': 'باحثة في مجال NLP مع خبرة 8 سنوات',
      'instructorKhaled': 'م. خالد عبدالله',
      'instructorKhaledBio': 'مهندس ذكاء اصطناعي في شركة تقنية رائدة',
      // Course objectives
      'understandMLBasics': 'فهم أساسيات تعلم الآلة',
      'buildSimpleModels': 'بناء نماذج بسيطة',
      'applyBasicAlgorithms': 'تطبيق الخوارزميات الأساسية',
      'understandAdvancedNLP': 'فهم النماذج المتقدمة في NLP',
      'buildComplexApps': 'بناء تطبيقات معقدة',
      'useTransformers': 'استخدام Transformers',
      'understandCNN': 'فهم CNN و شبكات التصنيف',
      'buildDetectionSystems': 'بناء أنظمة كشف الأجسام',
      'practicalImageVideo': 'تطبيقات عملية في الصور والفيديو',
      'pythonBasics': 'أساسيات لغة Python',
      'aiLibraries': 'المكتبات الأساسية للذكاء الاصطناعي',
      'buildPracticalProjects': 'بناء مشاريع عملية',
      'understandGPT': 'فهم تقنيات GPT وLLMs',
      'buildWithAPIs': 'بناء تطبيقات باستخدام APIs',
      'professionalPromptEng': 'Prompt Engineering احترافي',
      'masterTensorflow': 'إتقان TensorFlow و Keras',
      'buildAdvancedModels': 'بناء نماذج متقدمة',
      'deployToProduction': 'نشر النماذج في الإنتاج',
      'dataAnalysisBasics': 'أساسيات تحليل البيانات',
      'pythonVisualization': 'التصور باستخدام Python',
      'descriptiveInferentialStats': 'الإحصاء الوصفي والاستدلالي',
      'aiBusinessStrategies': 'استراتيجيات AI للأعمال',
      'processAutomation': 'أتمتة العمليات',
      'dataAnalysisDecisions': 'تحليل البيانات للقرارات',
      // Requirements
      'basicProgramming': 'معرفة أساسية بالبرمجة',
      'desireToLearn': 'رغبة في التعلم',
      'pythonExperience': 'خبرة في Python',
      'nlpBasics': 'معرفة بأساسيات NLP',
      'mlBasics': 'أساسيات تعلم الآلة',
      'noRequirements': 'لا توجد متطلبات سابقة',
      'basicMath': 'معرفة أساسية بالرياضيات',
      'businessExperience': 'خبرة في مجال الأعمال',
      // Community
      'communityTitle': 'المجتمع',
      'recent': 'الأحدث',
      'popular': 'الأكثر شعبية',
      'comments': 'التعليقات',
      'now': 'الآن',
      'vote': 'تصويت',
      // Community post content
      'discussionTitle1': 'أفضل خوارزمية ML للمبتدئين؟',
      'discussionContent1': 'أنا جديد في تعلم الآلة ومتحير في اختيار الخوارزمية المناسبة للبدء. أي اقتراحات؟',
      'discussionTitle2': 'مقارنة الأداء: GPT-4 مقابل Claude',
      'discussionContent2': 'هل قام أحد بمقارنة مفصلة بين GPT-4 وClaude؟ أنا مهتم بالدقة للنصوص العربية.',
      'discussionTitle3': 'أفكار مشاريع رؤية الحاسوب',
      'discussionContent3': 'أبحث عن أفكار مشاريع CV مثيرة لمحفظة أعمالي. يفضل شيء متعلق بـ OCR العربية.',
      'discussionTitle4': 'نصائح لمعالجة اللغة العربية',
      'discussionContent4': 'أعمل على مشروع تحليل المشاعر العربية. أي نصائح أو مصادر تنصحون بها؟',
      // User names
      'userName1': 'أحمد علي',
      'userName2': 'سارة محمد',
      'userName3': 'عمر حسن',
      'userName4': 'فاطمة إبراهيم',
      // News
      'newsTitle': 'الأخبار',
      'newsAll': 'الكل',
      'newResearch': 'أبحاث جديدة',
      'productsApplications': 'منتجات وتطبيقات',
      'investmentFunding': 'استثمارات وتمويل',
      'aiEthics': 'أخلاقيات الذكاء الاصطناعي',
      // News articles
      'newsArticle1Title': 'OpenAI تعلن عن GPT-5: نموذج لغوي ثوري',
      'newsArticle1Description': 'كشفت OpenAI عن GPT-5 بقدرات استثنائية في الاستدلال والفهم متعدد اللغات، خاصة للعربية.',
      'newsArticle2Title': 'اختراق Google DeepMind في الذكاء الاصطناعي الطبي',
      'newsArticle2Description': 'نظام ذكاء اصطناعي جديد يحقق دقة 95% في الكشف المبكر عن السرطان، مما يبشر بثورة في التشخيص الطبي.',
      'newsArticle3Title': 'Meta تطلق نموذج لغوي عربي مفتوح المصدر',
      'newsArticle3Description': 'نموذج Meta الجديد المدرب على بيانات عربية يظهر أداءً متفوقاً في اللهجات المحلية.',
      'newsArticle4Title': 'استثمارات الذكاء الاصطناعي تصل لرقم قياسي 50 مليار دولار',
      'newsArticle4Description': 'تمويل رأس المال المغامر في شركات الذكاء الاصطناعي يحطم الأرقام القياسية، مع التركيز على الأسواق الناشئة.',
      'newsArticle5Title': 'الاتحاد الأوروبي يصدر إرشادات جديدة لتنظيم الذكاء الاصطناعي',
      'newsArticle5Description': 'ينشر الاتحاد الأوروبي إطار عمل شامل لحوكمة الذكاء الاصطناعي، يضع معايير عالمية للتطوير الأخلاقي.',
      // News sources
      'newsSource1': 'تك كرانش',
      'newsSource2': 'MIT مراجعة التكنولوجيا',
      'newsSource3': 'أخبار الذكاء الاصطناعي',
      'newsSource4': 'رويترز',
      'newsSource5': 'نيتشر AI',
      // Payment translations  
      'continueToPayment': 'المتابعة للدفع',
      'purchaseDetails': 'تفاصيل الشراء',
      'taxIncluded': 'شامل الضريبة',
      'recommended': 'موصى به',
      'securePayments': 'جميع المعاملات آمنة ومشفرة بتقنية SSL',
      'enrolledSuccessfully': 'تم التسجيل في الدورة المجانية بنجاح!',
      'enrollNowFree': 'سجل الآن مجاناً',
      'buyNow': 'اشترِ الآن',
      // Quick Actions
      'quickActions': 'إجراءات سريعة',
      'exploreCourses': 'استكشف الدورات',
      'myCourses': 'دوراتي',
      'myCertificates': 'شهاداتي',
      // Course Details
      'courseProgress': 'التقدم في الدورة',
      'completed': 'مكتمل',
      'viewCertificate': 'عرض الشهادة',
      'educationalObjectives': 'الأهداف التعليمية',
      'requirements': 'المتطلبات',
      'enrolledInCourse': 'مسجل في الدورة',
      'progress': 'التقدم',
      'continueLeaming': 'متابعة التعلم',
      'rewatch': 'إعادة المشاهدة',
      'studentsEnrolled': 'طالب مسجل',
      // My Courses
      'myCoursesTitle': 'دوراتي',
      'inProgress': 'قيد التقدم',
      'completedStatus': 'مكتملة',
      'noCoursesEnrolled': 'لم تسجل في أي دورة بعد',
      'noCoursesInProgress': 'لا توجد دورات قيد التقدم',
      'noCoursesCompleted': 'لم تكمل أي دورة بعد',
      'startLearningToday': 'ابدأ رحلة التعلم اليوم',
      'browseCourses': 'تصفح الدورات',
      'continueButton': 'متابعة',
      'getCertificate': 'احصل على الشهادة',
      'lastAccessedOn': 'آخر دخول في',
      'lessons': 'دروس',
      'hours': 'ساعات',
      'quizzes': 'اختبارات',
      'lesson': 'درس',
      'hour': 'ساعة',
      'quiz': 'اختبار',
      // Certificates
      'certificatesTitle': 'شهاداتي',
      'noCertificatesYet': 'لا توجد شهادات بعد',
      'completeCourseToEarn': 'أكمل الدورات للحصول على الشهادات',
      'certificateOf': 'شهادة',
      'completion': 'إتمام',
      'issuedOn': 'صدرت في',
      'issuedDate': 'تاريخ الإصدار',
      'certificateNumber': 'رقم الشهادة',
      'studentName': 'اسم المتدرب',
      'instructorName': 'المدرب',
      'level': 'المستوى',
      'totalHours': 'عدد الساعات',
      'finalGrade': 'الدرجة النهائية',
      'download': 'تحميل',
      'share': 'مشاركة',
      'downloadingCertificate': 'جاري تحميل الشهادة...',
      'certificateDownloaded': 'تم تحميل الشهادة بنجاح',
      'shareCertificate': 'مشاركة الشهادة',
      'copyLink': 'نسخ الرابط',
      'linkCopied': 'تم نسخ الرابط!',
      'downloadCertificate': 'تحميل الشهادة',
      // Lesson Player
      'lessonPlayer': 'مشغل الدروس',
      'completeAndContinue': 'إكمال والمتابعة',
      'nextLesson': 'الدرس التالي',
      'previousLesson': 'الدرس السابق',
      'courseMaterials': 'مواد الدورة',
      'discussion': 'النقاش',
      'notes': 'الملاحظات',
      'transcript': 'النص المكتوب',
      // Community
      'createPost': 'إنشاء منشور',
      'whatsOnYourMind': 'بماذا تفكر؟',
      'postTitle': 'عنوان المنشور',
      'postContent': 'محتوى المنشور',
      'publish': 'نشر',
      'cancel': 'إلغاء',
      'writeComment': 'اكتب تعليقاً...',
      'post': 'نشر',
      'reply': 'رد',
      'noComments': 'لا توجد تعليقات بعد',
      'beFirstToComment': 'كن أول من يعلق',
      'loadingComments': 'جاري تحميل التعليقات...',
      'viewAllComments': 'عرض جميع التعليقات',
      'hideComments': 'إخفاء التعليقات',
      // Profile
      'editProfileTitle': 'تعديل الملف الشخصي',
      'bio': 'نبذة',
      'location': 'الموقع',
      'website': 'الموقع الإلكتروني',
      'save': 'حفظ',
      'profileUpdated': 'تم تحديث الملف الشخصي بنجاح',
      'changeProfilePicture': 'تغيير صورة الملف الشخصي',
      // Settings
      'settingsTitle': 'الإعدادات',
      'accountSettings': 'إعدادات الحساب',
      'notificationSettings': 'إعدادات الإشعارات',
      'privacySettings': 'إعدادات الخصوصية',
      'pushNotifications': 'الإشعارات الفورية',
      'emailNotifications': 'إشعارات البريد الإلكتروني',
      'darkTheme': 'المظهر الداكن',
      'lightTheme': 'المظهر الفاتح',
      'systemDefault': 'الافتراضي للنظام',
      'about': 'حول',
      'version': 'الإصدار',
      'termsOfService': 'شروط الخدمة',
      'helpSupport': 'المساعدة والدعم',
      // General
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'success': 'نجاح',
      'warning': 'تحذير',
      'info': 'معلومة',
      'yes': 'نعم',
      'no': 'لا',
      'ok': 'موافق',
      'close': 'إغلاق',
      'delete': 'حذف',
      'edit': 'تعديل',
      'update': 'تحديث',
      'submit': 'إرسال',
      'confirm': 'تأكيد',
      'back': 'رجوع',
      'next': 'التالي',
      'skip': 'تخطي',
      'done': 'تم',
      'search': 'بحث',
      'filter': 'تصفية',
      'sort': 'ترتيب',
      'refresh': 'تحديث',
      'loadMore': 'تحميل المزيد',
      'showLess': 'عرض أقل',
      'showMore': 'عرض المزيد',
      'seeAll': 'عرض الكل',
      'noData': 'لا توجد بيانات',
      'noResults': 'لا توجد نتائج',
      'tryAgain': 'حاول مرة أخرى',
      'somethingWentWrong': 'حدث خطأ ما',
      'pleaseWait': 'يرجى الانتظار...',
      'networkError': 'خطأ في الشبكة. يرجى التحقق من الاتصال.',
      'sessionExpired': 'انتهت صلاحية الجلسة. يرجى تسجيل الدخول مرة أخرى.',
      'unauthorized': 'وصول غير مصرح به',
      'pageNotFound': 'الصفحة غير موجودة',
      'backToHome': 'العودة للرئيسية',
    },
  };
  
  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();
  
  @override
  bool isSupported(Locale locale) {
    return ['en', 'ar'].contains(locale.languageCode);
  }
  
  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }
  
  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}